#!/usr/bin/env node
// Generates supabase/seed.sql from the JSON data files.
// Run: node tools/gen-seed.js
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const read = (f) => JSON.parse(fs.readFileSync(path.join(root, f), 'utf8'));
const cocktails = read('cocktails.json');
const mocktails = read('mocktails.json');
const inventory = read('ingredients.json');

const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const arr = (xs) => `array[${(xs || []).map(q).join(', ')}]::text[]`;
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

// Guess a category for auto-added recipe ingredients (keyword, first match wins).
const CATEGORY_RULES = [
  [/bitters/i, 'Bitters'],
  [/vermouth/i, 'Wine'],
  [/liqueur|cointreau|campari|disaronno|amaretto|st-germain|b.?n.?dictine|chile/i, 'Liqueurs'],
  [/juice|lime$|lemon$/i, 'Juices'],
  [/syrup|sugar|honey/i, 'Syrups'],
  [/soda|water|tonic|top/i, 'Top Up'],
  [/rum|gin|vodka|whisk|scotch|bourbon|tequila|prosecco/i, 'Spirits'],
];
const guessCategory = (name) => (CATEGORY_RULES.find(([re]) => re.test(name)) || [, 'Uncategorized'])[1];

// --- ingredients: inventory first, then placeholders for missing recipe names ---
const byName = new Map(inventory.map((i) => [i.name, i]));
const used = new Set();
for (const r of [...cocktails, ...mocktails]) for (const n of r.ingredients || []) used.add(n);

const placeholders = [];
for (const name of used) {
  if (byName.has(name)) continue;
  const cat = guessCategory(name);
  placeholders.push({ id: slug(`${cat}-${name}`), name, category: cat, brand: null, status: 'can-get', notes: 'auto-added for recipe FK' });
}

const ingredientRows = [...inventory, ...placeholders].map(
  (i) => `  (${q(i.id)}, ${q(i.name)}, ${q(i.category)}, ${q(i.brand)}, ${q(i.status)}, ${q(i.notes)})`
);

// --- recipes + recipe_ingredients ---
const recipeRows = [];
const linkRows = [];
const addRecipe = (r, kind) => {
  recipeRows.push(
    `  (${q(r.id)}, ${q(r.name)}, ${q(kind)}, ${q(r.baseSpirit || r.baseIngredient)}, ` +
      `${arr(r.tags)}, ${arr(r.glasses)}, ${arr(r.garnishes)}, ` +
      `${q(r.history)}, ${q(r.description)}, ${q(r.recipe)}, ${q(r.mood)})`
  );
  (r.ingredients || []).forEach((name, i) => {
    linkRows.push(`  (${q(r.id)}, ${i}, ${q(name)}, ${q((r.measurementsMl || [])[i])}, ${q((r.measurementsOz || [])[i])})`);
  });
};
cocktails.forEach((r) => addRecipe(r, 'cocktail'));
mocktails.forEach((r) => addRecipe(r, 'mocktail'));

const sql = `-- Generated by tools/gen-seed.js — do not edit by hand.
begin;

insert into ingredients (id, name, category, brand, status, notes) values
${ingredientRows.join(',\n')}
on conflict (id) do nothing;

insert into recipes (id, name, kind, base, tags, glasses, garnishes, history, description, instructions, mood) values
${recipeRows.join(',\n')}
on conflict (id) do nothing;

insert into recipe_ingredients (recipe_id, position, ingredient_name, measurement_ml, measurement_oz) values
${linkRows.join(',\n')}
on conflict (recipe_id, position) do nothing;

commit;
`;

const out = path.join(root, 'supabase', 'seed.sql');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, sql);
console.log(`wrote ${out}`);
console.log(`  recipes:            ${recipeRows.length}`);
console.log(`  ingredients:        ${ingredientRows.length} (${inventory.length} inventory + ${placeholders.length} auto-added)`);
console.log(`  recipe_ingredients: ${linkRows.length}`);
